data_dir: ../dataset
default:
  overwrite: false
  video_name: rene
  max_object_size: 0.3
  low_threshold: 0.5
  high_threshold: 0.8
  enforce_iframes: true
  verbosity: info
  simulate: false
  hname: false
  intersection_threshold: 1
  low_results_path: None
  high_results_path: None
  high_resolution: -1
  high_qp: -1
  estimate_banwidth: false
  low_images_path: None
  tracker_length: 4
  batch_size: 5
  min_object_size: 0
  boundary: 0.2
  tracking_threshold: 0.3
  suppression_threshold: 0.5
  rpn_enlarge_ratio: 0
  prune_score: 0.5
  objfilter_iou: 0.8
  size_obj: 0.4
  debug_mode: false
  ground_truth: false
  mode: emulation
  adaptive_mode: true
  adaptive_test_display: SEPARATED-10500
  profile_folder_name: profile-separated
instances:
  - method: gt
    low_qp: 24
    low_resolution: 1
  - method: mpeg
    low_qp:
      - 30
      - 32
      - 34
    low_resolution:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      - 0.7
      - 0.8
  - method: dds
    mode: emulation
    debug_mode: false
    high_qp:
      - 24
    high_resolution:
      - 1
    low_qp:
      - 30
    low_resolution:
      - 0.8
